spring.datasource:
  url: jdbc:mysql://localhost/garden_db?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password:
  driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080

spring:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update